<?php

return [
    'enabled' => (bool) env('DOCINTEL_INTELLIGENCE_V2', false),
    'workspaces' => [],
    'brief' => (bool) env('DOCINTEL_V2_BRIEF', true),
    'charts' => (bool) env('DOCINTEL_V2_CHARTS', true),
    'values' => ['parser_version' => 'values.v1'],
    'tier1' => [
        'min' => 5, 'target' => 8, 'max' => 10, 'forced_max' => 8, 'hard_cap' => 18,
        'per_kind' => 3, 'per_stem' => 2, 'imminent_days' => 90, 'recompute_after_hours' => 24,
        'origin_quotas' => ['synthesis' => 4, 'metric' => 3, 'trend' => 2, 'risk' => 2, 'obligation' => 1],
    ],
    'materiality' => [
        'version' => '1',
        'class_base' => [
            'critical_risk' => 0.94, 'high_risk' => 0.82, 'upcoming_obligation' => 0.82,
            'dated_obligation' => 0.64, 'undated_obligation' => 0.56, 'risk' => 0.56,
            'metric' => 0.36, 'fact' => 0.36, 'definition' => 0.24, 'entity' => 0.24, 'other' => 0.08,
        ],
        'weights' => [
            'severity' => 0.010, 'date_proximity' => 0.010, 'date_resolution' => 0.005,
            'attribution_authority' => 0.005, 'obligation_consequence' => 0.010,
            'structural_prominence' => 0.020, 'monetary_magnitude' => 0.060,
            'relative_magnitude' => 0.020, 'comparability' => 0.020,
            'repetition_penalty' => -0.020, 'boilerplate_penalty' => -0.040,
            'unresolved_penalty' => -0.020, 'cited_by_synthesis' => 0.000,
        ],
        'bands' => ['tier1' => 0.72, 'tier2' => 0.45, 'tier3' => 0.18],
        'signals' => [
            'severity' => ['critical' => 1.0, 'high' => 0.7, 'medium' => 0.35, 'low' => 0.1],
            'date_proximity' => ['imminent_days' => 90, 'horizon_days' => 365,
                'floor_value' => 0.2, 'falloff' => 0.8],
            'date_resolution' => ['calendar' => 1.0, 'period' => 0.6, 'relative' => 0.3, 'unknown' => 0.0],
            'attribution_authority' => ['regulator' => 1.0, 'auditor' => 1.0,
                'counterparty' => 0.6, 'quoted' => 0.3, 'third_party' => 0.3],
            'structural_prominence' => ['heading_span_types' => ['heading'],
                'heading_value' => 1.0, 'ordinal_first_fraction' => 0.10, 'ordinal_value' => 0.5],
            'boilerplate_penalty' => ['boilerplate_span_types' => []],
            'monetary_magnitude' => ['singleton_value' => 0.5],
        ],
        'date_role_patterns' => [
            'effective_date' => ['effective from', 'effective on', 'with effect from', 'takes effect', 'comes into force'],
            'due_date' => ['due by', 'due on', 'due in', 'deadline', 'no later than'],
            'expiry_date' => ['expires', 'valid until', 'terminates on'],
            'issued_date' => ['signed on', 'executed on', 'issued on'],
            'as_of_date' => ['as at', 'as of'],
            'period_covered' => ['for the year ended', 'for the period'],
            'observed_date' => ['occurred', 'struck', 'was held', 'took place'],
            'review_date' => ['review date', 'to be reviewed'],
        ],
        'must_be_by_max_intervening_words' => 6,
        'penalty_patterns' => ['penalty', 'penalties', 'liquidated damages', 'late fee',
            'default interest', 'forfeit', 'service credit', 'termination for'],
        'forced_priorities' => [
            'critical_risk' => 10, 'imminent_dated_obligation' => 20, 'overdue_dated_obligation' => 30,
            'penalised_obligation' => 40, 'high_risk' => 50, 'regulator_attributed' => 60,
            'headline_measure' => 70, 'unresolved_material_reference' => 80,
        ],
        'tiebreak' => ['absent_forced_priority' => 999,
            'kind_order' => ['obligation', 'deadline', 'risk', 'metric', 'fact', 'definition', 'entity', 'unresolved']],
    ],
];
